### ISSUE TITLE
Opencart

### ISSUE THREAD

**Issue by coolhaka** [hiteshsahu/ECommerce-App-Android-#1]
How can i connect your app to my opencart 1.5.6.4 based store?

**Comment by hiteshsahu** [comment]
If open cart provide public api then yes you can. Use Retrofit to access your products and link them  ti this app.

**Comment by coolhaka** [comment]
Please give me a opencart api extension by which i can make an app from your script.

**Comment by hiteshsahu** [comment]
The issue is too broad and not related to the source code.
