### ISSUE TITLE
Start up issue

### ISSUE THREAD

**Issue by vlchz** [hiteshsahu/ECommerce-App-Android-#3]
When I was trying to upload the project it said two of the modules could not be found. The error stated: "Failed to find target with hash string 'android-23' in: C:/........

Please help!

Thank you

**Comment by hiteshsahu** [comment]
Please Add some screenshots or at least stack track.

**Comment by vlchz** [comment]
I figured it out. I had to download some sdk's and update some stuff. Thank you!
