### ISSUE TITLE
web api for ecommerce android app

### ISSUE THREAD

**Issue by sagarpawar1123** [hiteshsahu/ECommerce-App-Android-#5]
Hello,

am trying to fetch data from database and display it in this android ecommerce app but facing lot of problem. i have managed to create different categories and fetch them and display. but problem is for products. am able to display data in logcat but can't display on screen.
 i have pasted the code that i have tried. please help ..

 public class getCosmetics extends AsyncTask<String, String, JSONObject> {

        ConcurrentHashMap<String, ArrayList<Product>> productMap = new ConcurrentHashMap<String, ArrayList<Product>>();
        ArrayList<Product> cosmenticslist = new ArrayList<Product>();

        @Override
        protected JSONObject doInBackground(String... params) {

            Log.d("jhjg", "nkkjjuihngbb");
            try {
                jsonObject = jsonParser.makeHttpRequest2(URL_COS, "POST");

                Log.d("json in cosmetics ", "> " + jsonObject.toString());
                if (jsonObject != null) {
                    System.out.println("inside if statement");
                    try {
                        jsonArray = jsonObject.getJSONArray("prdct");

                        Log.d("Json array", "" + jsonArray);

                        for (int i = 0; i < jsonArray.length(); i++) {

                            JSONObject jsonObject1 = jsonArray.getJSONObject(i);

                            String pid = jsonObject1.getString("pid");
                            pname = jsonObject1.getString("pname");
                            long_descp = jsonObject1.getString("short_descp");
                             short_descp = jsonObject1.getString("long_descp");
                             mrp = jsonObject1.getString("mrp");
                             saleprice = jsonObject1.getString("saleprice");
                            discount = jsonObject1.getString("discount");
                            imageurl = jsonObject1.getString("imageurl");

                            Log.d("products->", "pid->" + pid + "pname->" + pname + "lo->" + long_descp + "short->" + short_descp + "mrp->" + mrp + "sale" + saleprice + "disc" + discount + "imahe" + imageurl);
                            cosmenticslist
                                    .add(new Product(
                                            pname,
                                            long_descp,
                                            short_descp,
                                            mrp,
                                            discount,
                                            saleprice,
                                            "0",
                                            imageurl,
                                            ""));

                        }

                        productMap.put("Cosmetics", cosmenticslist);
                        GlobaDataHolder.getGlobaDataHolder().setProductMap(productMap);
                    } catch (JSONException e) {
                        e.printStackTrace();
                        //  Toast.makeText(getApplicationContext(),"No Records Found", Toast.LENGTH_LONG).show();
                    }

                } else {
                    //  Toast.makeText(getApplicationContext(),"Unable to load data",Toast.LENGTH_LONG).show();
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

            return jsonObject;

        }

am calling this method from getAllProducts() method.

**Comment by hiteshsahu** [comment]
Update UI only after Async Task completion/failure by calling `setUpUi(); ` method.
